/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Insight model
type Insight struct {
	InsightID string `json:"insightID,omitempty"`

	DataID string `json:"dataID,omitempty"`
}
