/*
 *
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

// Data model
type Data struct {
	DataID string
	content Content
	Score int64
}
type Content struct {
        Name string
    	Body string
    	Time int64
}

